### ISSUE TITLE
Can't find variable document

### ISSUE THREAD

**Issue by Zacaria** [browniefed/pdxlivebus#2]
Hello,

I just found your project and it looks great !
However I currently struggle to make your project work on my emulated device.

![](https://cloud.githubusercontent.com/assets/5860751/16762536/1cf4006c-4825-11e6-8307-0ba9b05dd9a1.png)

I know this is a problem with leaflet and react-native and I hoped that you found a workaround.

The commands i run :
`npm run dev`
`npm start`

My system : Xubuntu 64
The emulator : Android Virtual Device
The emulated : nexus 6 x86_64 - Android API 23

Thank you for your work :)

**Comment by browniefed** [comment]
Woops. Fixed it for the web then broke it for react native :)
Delete this code in this commit and it'll run.
Here ist he commit
https://github.com/browniefed/pdxlivebus/commit/b34c73a08eb9d4aa79ca0c1a519ec882e25098f1

Just remove the `&& !document` portion.

**Comment by browniefed** [comment]
This doesn't use leaflet for React Native, this uses https://github.com/lelandrichardson/react-native-maps which you'll probably want to use if you are doing maps on React Native

**Comment by browniefed** [comment]
So I posted 2 comments, but they didn't apparently submit?

The issue here is some code I wrote to fix the web version but broke react native.
I think I fixed it with the latest commit, so pull latest and you should maybe be good to go.
If not let me know.


Leaflet won't work on React Native. I would recommend using https://github.com/lelandrichardson/react-native-maps instead.

**Comment by browniefed** [comment]
I think I fixed it in master, go ahead and pull latest and it should theoretically work.

**Comment by Zacaria** [comment]
I confirm that the map now is displayed. Thank you !

**Comment by browniefed** [comment]
Fantastic.
